language: node_js
node_js:
- v8.4.0
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: 
- greenkeeper-lockfile-upload
- npm run coverage
env:
  global:
  - secure: zMAuk0Bz5EV9Je/SvNtO6M2osfTVDoAe1hRJAPEePKxC7G/Bln6+gFYaAzKpcZ0F2BlRmOEgz3fqDDE3RG424DiZ49HBs1ZDAO0klmcyQGKC/KetQfcRunVCcrZhjVznXONdLXDgCFEX6S5TiFnr63meLHocii9ROcKtFW7SGmRalD4qqRBjv43T9q+LUxOhCuBr74IjNflpZ5+Q6UmqHVr3xCtmXgbKSgUj5hyEb9eqUZVfwhjN9GpkmU4caiQn3ErrXm+3yvnMzxA/rAJsT7kCsxmQ8omIouR8HAwN08EtdeYAD2u+oH5c4cwQ7uWilc5bNkxED4afozxuuZi3T9mKEOszunGZu3DTOvBqLz6YCGs668R9ZGeqnN4ufd0thE4KyLgoBFrrilZDgGIVcRj/iP0nrTrvdFIjMT3JYbJQKT5SX1i+ncJ/UsOcdt6eBAo90DMk+24lqt6nqfcbNljE3Lmsra+oy0niVRZRs43Ed+Sy843DeyEE6utVDxaDzrWgT30WPfOcj/y8wk+W5Xh38Qu23kMCqbOesAwD4Qq2aDV3YGz/N2nLooFSx5UNWwlHEQRPgRc6u4WWFdJzsO7JLHWaKXC0OfDGcPVmWsZ2lD7Eo7J/Pm6UCTGXXrEWYyEraF0r7gaPQ6/g/i0VKiC6Z5sra13f/tQQruVO1j0=
  - secure: sUqFcqEHszKlCE/PVx31R31aLV9fIx4tENKMbuWBEUE2LesHNt4NP/Q0F5vp50ddzvM14zPs1CKsp+vGYbt6KAC3wnbGFdHLv+YDuBTrUdkQV5vnetG/z+yEzMttIwXEcW6dJcUn/9C1z1OUK3MeuRpDrwxuWkHS7yxoDKN7ClZpuRgllScGzhutyKuxXBNSd1C8ImaKZR+IVwrsZr4WblMMKeYYwE7+wvvHKKCEJ/bBk2SJ1fjvLupXPRppvEhkoix4HPrD876H6EiCcYgxxN2h9wLVkkq4dsSkibdkCuC0kJ5YzGWHPFj/rilYTbtj3p6/YpG/YvYFJXISwcdSr9viGEcfuV1DyrnWwk3vIWewkDNSo00kw1Pd+L0OIlpWRvQw2D+hgyCfHm0NwInmvrdiNvBs3zzOGodyzmzDaiuqeEEmuDvO763YbokPy5higlbKL5MsmDK21WX68jKcMIFJBTBcVGq3HfhYe9Rdnxxsu+J1vEtAuYglufM0ox0m6Jwwf0nIRvf0GiRG4phKcANMU6QSfHCyamORY6PSfPnRCHpVaCGa2Ggw0yybMxf3uH2xV20eswTO1dwq9sRNc+cjkXlAfKX7V4IXIDeeeV4W+K3Hi46aavfm0ZGg9WYeqRcyJT4jb+e10H4s3ES2jrpvbEum9b3lDKqc012XaaI=
